routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('hello_world','HelloController@hello_world');

Route::get('sites/export','SiteController@export');

Route::post('clone_site','SiteController@clone_site');

Route::post('backup_site','SiteController@backup_site');

Route::post('restore_backup_site','SiteController@restore_backup_site');

Route::get('sites/get_sites','SiteController@get_sites');

Route::get('sites/trash','SiteController@trash');

Route::get('sites/backups','SiteController@backups');

Route::post('delete_backup','SiteController@delete_backup');

Route::get('sites/suspend','SiteController@suspend');

Route::get('sites/site_continue','SiteController@site_continue');

Route::get('sites/restore','SiteController@restore');

Route::post('force_delete', 'SiteController@force_delete');

Route::get('update_license','OregisterController@update_license');

Route::get("reload_server",'SiteController@reload_server');

Route::get('register_your_license','OregisterController@register_your_license');

Route::resource("sites","SiteController");
Route::resource("options","OptionController");

// Authentication routes...
/*
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout');

/**
 * Register Route(s)
 */
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

//Admin Routes
Route::get('/list_users', 'AdminController@list_users');
Route::get('/edit_user', 'AdminController@edit_user');
Route::get('/create_user', 'AdminController@create_user');
Route::post('/delete_user', 'AdminController@delete_user');
Route::get('/phpmyadmin_panel','AdminController@phpmyadmin_panel');
Route::get('/phpinfo_panel','AdminController@phpinfo_panel');
Route::post('/change_php','AdminController@change_php');
Route::post('/store_user','AdminController@store_user');
Route::post('/update_user','AdminController@update_user');

//BASE ROUTES
Route::get('/premium_plugins','BaseController@premium_plugins');
Route::post('/pete_plugins_install','BaseController@pete_plugins_install');
Route::post('/pete_plugins_update','BaseController@pete_plugins_update');
Route::post('/pete_update','BaseController@pete_update');
Route::post('/validate_pete','BaseController@validate_pete');
Route::get('/get_ads','BaseController@get_ads');
Route::get('/phpinfo_view','BaseController@phpinfo_view');

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


Route::get('/get_domains', function () {
	
	$sites = Site::orderBy('id', 'desc')->get();
    return response()->json($sites);
});


Route::get('/', array('as' => 'sites.index', 'uses' => 'SiteController@index'));

app/Option.php
<?php

namespace App;
use Log;
use Illuminate\Database\Eloquent\Model;

class Option extends Model
{
    //
	protected $table = 'options';
	
	public static function delete_meta_value($key){
		$object = Option::where('option_name',$key)->first();
		if($object){
		   $object->delete();
		}
	}
	
	public static function get_meta_value($key){
		$object = Option::where('option_name',$key)->first();
		if(isset($object)){
			return $object->option_value;
		}else{
			return "";
		}		
	}
}

app/Http/Controllers/OptionController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Log;
use App\Option;
use Illuminate\Http\Request;
use View;
use Illuminate\Support\Facades\Auth;

class OptionController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
	public function __construct(Request $request){
	    
	    $this->middleware('auth');
		$this->middleware('auth.admin');
		
		$dashboard_url = env("DASHBOARD_URL");
		$viewsw = "/options";
		
		//DEBUGING PARAMS
		$debug = env('DEBUG');
		if($debug == "active"){
			$inputs = $request->all();
			Log::info($inputs);
		}
		
		$system_vars = parent::__construct();
		$pete_options = $system_vars["pete_options"];
		$sidebar_options = $system_vars["sidebar_options"];
		
		View::share(compact('dashboard_url','viewsw','pete_options','system_vars','sidebar_options'));
		   
	}
	
	public function index()
	{
		
		$options = Option::where("visible",true)->orderBy('id', 'desc')->paginate(25);
		$current_user = Auth::user(); 
		return view('options.index', compact('options','current_user'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$option = new Option();
		$current_user = Auth::user(); 
		return view('options.create',compact('option','current_user'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		
		$option = new Option();

		$option->option_name = $request->input("option_name");
        $option->option_value = $request->input("option_value");
		$option->order = $request->input("order");
		$option->category = $request->input("category");
		$option->title = $request->input("title");
		$option->version = $request->input("version");
		$option->visible = true;
		$option->save();

		return redirect()->route('options.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$option = Option::findOrFail($id);
		$current_user = Auth::user(); 
		return view('options.show', compact('option'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		
		$option = Option::findOrFail($id);
		$current_user = Auth::user(); 
		return view('options.edit', compact('option','current_user'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$option = Option::findOrFail($id);

		$option->option_name = $request->input("option_name");
        $option->option_value = $request->input("option_value");
		$option->order = $request->input("order");
		$option->category = $request->input("category");
		$option->title = $request->input("title");
		$option->version = $request->input("version");
		
		$option->save();

		return redirect()->route('options.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$option = Option::findOrFail($id);
		$option->delete();

		return redirect()->route('options.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/options/_form.blade.php
<br />
     
<label for="option_name-field">Option_name</label>
<input type="text" id="option_name-field" name="option_name" class="form-control" value="{{ $option->option_name }}"/>
                      
<label for="option_value-field">Option_value</label>
<input type="text" id="option_value-field" name="option_value" class="form-control" value="{{ $option->option_value }}"/>

<label for="option_value-field">Order</label>
<input type="text" id="order" name="order" class="form-control" value="{{ $option->order }}"/>
                     
<label for="option_value-field">Category</label>
<input type="text" id="category" name="category" class="form-control" value="{{ $option->category }}"/>

<label for="option_value-field">Title</label>
<input type="text" id="title" name="title" class="form-control" value="{{ $option->title }}"/>

<label for="option_value-field">Version</label>
<input type="text" id="version" name="version" class="form-control" value="{{ $option->version }}"/>

<br />

resources/views/options/create.blade.php
@extends('layout')

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">
			
			<h3>Create new Option</h3>
			
            <form action="{{ route('options.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                @include('options/_form')
               
                <button type="submit" id="create_button" class="btnpete">Create</button>
                
            </form>

        </div>
    </div>
@endsection

resources/views/options/edit.blade.php
@extends('layout')

@section('header')
   
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('options.update', $option->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                @include('options/_form')
					
                 <button type="submit" id="update_button" class="btnpete">Update</button>
				 
            </form>

        </div>
    </div>
@endsection

resources/views/options/index.blade.php
@extends('layout')

@section('header')
  
@endsection

@section('content')

    <div class="row">

        <div class="col-md-12">
	        	
				<h1><a class="btn btn-success pull-right" href="/options/create"><i class="glyphicon glyphicon-plus"></i> Create option</a></h1>
	        
		</div>
	</div>

    <div class="row">
        <div class="col-md-12">
			
	        
			
			<div class="content table-responsive table-full-width">
			                               
            @if($options->count())
                 <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>OPTION_NAME</th>
                        <th>OPTION_VALUE</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($options as $option)
                            <tr>
                                <td>{{$option->id}}</td>
                                <td>{{$option->option_name}}</td>
                    <td>{{$option->option_value}}</td>
                                <td class="text-right">
                                    
                                    <a class="btn btn-xs btn-warning" id= "edit_{{$option->option_name}}" href="{{ route('options.edit', $option->id) }}">Edit</a>
                                    <form action="{{ route('options.destroy', $option->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" id="delete_{{$option->option_name}}" class="btn btn-xs btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $options->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif
			 </div>
        </div>
    </div>

@endsection

resources/views/options/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Options / Show #{{$option->id}}</h1>
        <form action="{{ route('options.destroy', $option->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('options.edit', $option->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="option_name">OPTION_NAME</label>
                     <p class="form-control-static">{{$option->option_name}}</p>
                </div>
                    <div class="form-group">
                     <label for="option_value">OPTION_VALUE</label>
                     <p class="form-control-static">{{$option->option_value}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('options.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection