routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('hello_world','HelloController@hello_world');

Route::get('sites/export','SiteController@export');

Route::post('clone_site','SiteController@clone_site');

Route::post('backup_site','SiteController@backup_site');

Route::post('restore_backup_site','SiteController@restore_backup_site');

Route::get('sites/get_sites','SiteController@get_sites');

Route::get('sites/trash','SiteController@trash');

Route::get('sites/backups','SiteController@backups');

Route::post('delete_backup','SiteController@delete_backup');

Route::get('sites/suspend','SiteController@suspend');

Route::get('sites/site_continue','SiteController@site_continue');

Route::get('sites/restore','SiteController@restore');

Route::post('force_delete', 'SiteController@force_delete');

Route::get('update_license','OregisterController@update_license');

Route::get("reload_server",'SiteController@reload_server');

Route::get('register_your_license','OregisterController@register_your_license');

Route::resource("sites","SiteController");
Route::resource("options","OptionController");

// Authentication routes...
/*
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout');

/**
 * Register Route(s)
 */
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

//Admin Routes
Route::get('/list_users', 'AdminController@list_users');
Route::get('/edit_user', 'AdminController@edit_user');
Route::get('/create_user', 'AdminController@create_user');
Route::post('/delete_user', 'AdminController@delete_user');
Route::get('/phpmyadmin_panel','AdminController@phpmyadmin_panel');
Route::get('/phpinfo_panel','AdminController@phpinfo_panel');
Route::post('/change_php','AdminController@change_php');
Route::post('/store_user','AdminController@store_user');
Route::post('/update_user','AdminController@update_user');

//BASE ROUTES
Route::get('/premium_plugins','BaseController@premium_plugins');
Route::post('/pete_plugins_install','BaseController@pete_plugins_install');
Route::post('/pete_plugins_update','BaseController@pete_plugins_update');
Route::post('/pete_update','BaseController@pete_update');
Route::post('/validate_pete','BaseController@validate_pete');
Route::get('/get_ads','BaseController@get_ads');
Route::get('/phpinfo_view','BaseController@phpinfo_view');

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


Route::get('/get_domains', function () {
	
	$sites = Site::orderBy('id', 'desc')->get();
    return response()->json($sites);
});


Route::get('/', array('as' => 'sites.index', 'uses' => 'SiteController@index'));

app/Http/Controllers/SiteController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Log;
use App\Site;
use App\Adomain;
use App\Secure;
use App\User;
use App\Backup;
use Illuminate\Support\Facades\Input;
use Response;
use App\App;
use Validator;
use App\Option;
use DB;
use App\Pete;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Illuminate\Support\Facades\Redirect;
use App\PeteOption;
use Illuminate\Routing\Route;
use Illuminate\Support\MessageBag;
use View;

class SiteController extends Controller {

	
	public function __construct(Request $request){
			
	    $this->middleware('auth');
		$dashboard_url = env("DASHBOARD_URL");
		$viewsw = "/sites";
		
		//DEBUGING PARAMS
		$debug = env('DEBUG');
		if($debug == "active"){
			$inputs = $request->all();
			Log::info($inputs);
		}
		
		$system_vars = parent::__construct();
		$pete_options = $system_vars["pete_options"];
		$sidebar_options = $system_vars["sidebar_options"];
		$os_distribution = $system_vars["os_distribution"];
		
		View::share(compact('dashboard_url','viewsw','pete_options','system_vars','sidebar_options','os_distribution'));	
	 }
	 
	 
	
	public function register_your_license(){
		
	
		$validation_url = Option::get_meta_value('validation_url');
		return view('oregisters.register_your_license', compact('validation_url'));
		
	}
	
	
	public function export(){
		
		$user = Auth::user();
		$tab_index = "index";
		$site = Site::findOrFail(Input::get('id'));
		
		if($site->app_name=="WordPress"){
			$site->export_wordpress();
		}else if(($site->app_name=="Drupal") || ($site->app_name=="drupal")){
			$site->export_drupal();
		}
		
		$exporturl = $site->file_to_download;
		
		if($user->admin){
			$sites = Site::orderBy('id', 'desc')->paginate(50);
		}else{
			$sites = $user->my_sites()->paginate(10);
		}
		
		
		return view('sites.index', compact('sites','exporturl','tab_index'));
	  
	}
	
	public function reload_server(){
		
		Site::reload_server();
		return response()->json(["OK" => "OK"]);  
	}
	
	public function trash(){
		
		$user = Auth::user();
		$sites = $user->my_trash_sites()->where("app_name","WordPress")->paginate(10);
		$tab_index = "trash";
		return view('sites.trash', compact('sites','tab_index'));
		
	}
	
	public function suspend(){
		
		$site = Site::findOrFail(Input::get('id'));
		$site->suspend = true;
		$site->suspend_wordpress();
		$site->save();
		return Redirect::to('/?success=true&site_id='.$site->id);
	  
	}
	
	public function site_continue(){
		
		$site = Site::findOrFail(Input::get('id'));
		$site->suspend = false;
		$site->continue_wordpress();
		$site->save();
		return Redirect::to('/?success=true&site_id='.$site->id);
	  
	}
	
	public function get_sites(){
		
		$app_name = Input::get('app_name');
		if($app_name == "Wordpress"){
		  $result = Site::where('app_name', "Wordpress")->orderBy('id', 'desc')->get();
		}else if($app_name == "Wordpress+laravel"){
		  $result = Site::where('app_name', "Wordpress")->orderBy('id', 'desc')->get();
		  for ($i = 0; $i < count($result); $i++) {
			if(substr_count($result[0]->domain, '.') > 2) {
				unset($array[$i]);
			}
			  
		  }
		}
	    return response()->json($result);
	  
	}
	
	
	public function restore(){
		$site = Site::withTrashed()->findOrFail(Input::get('id'));
		$site->restore();
		$site->restore_wordpress();
		return Redirect::to('/?success=true&site_id='.$site->id);
	}
	
	public function clone_site(){
		
		$user = Auth::user();
		$clone_domain = Input::get('clone_domain');
		$site_to_clone_id = Input::get('site_to_clone_id');
		$clone_domain = preg_replace("/\s+/", "", $clone_domain);
		$site_name = str_replace(".","",$clone_domain);
		
		if($clone_domain == ""){
			return response()->json(['message'=> "Empty Domain"]);
		}
		
		$site = Site::where("url",$clone_domain)->first();
		if(isset($site)){
			return response()->json(['message'=> "Domain Taken"]);
		}
		
		if($site_name){
			
			$forbidden_names = array("filemanager", "ssl", "localhost", "pete", "pete2","html", "Pete", "Pete2");
		
			if (in_array($site_name, $forbidden_names)) {
				return response()->json(['message'=> "Forbidden project name"]);
			}
		}
			
		$site_to_clone = Site::findOrFail($site_to_clone_id);
		$backup = $site_to_clone->snapshot_creation("oclone");	

		$base_path = base_path();
		$backup_file = "$base_path/backups/$backup->site_id/".$backup->file_name;	
			
		$site = new Site();
		$site->action_name = "Clone";
		$site->name = $site_name;
		$site->url = $clone_domain;
		$site->wp_user = $backup->wp_user;
		$site->theme = $backup->theme;
		$site->user_id = $user->id;
		$site->first_password = $backup->first_password;
		$site->barserver_id = $backup->barserver_id;
		$site->backup_days = 2;
		$db_name = "db_" . substr(str_shuffle("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), 0, 10);
		$db_user = "usr_" . substr(str_shuffle("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), 0, 10);
		$db_user_pass = substr(str_shuffle("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), 0, 10); 
		$site->import_wordpress($backup_file,["db_name" => $db_name, "db_user" => $db_user, "db_user_pass" => $db_user_pass]);

		$backup->delete();
		
		return response()->json(['ok' => 'OK']);
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$user = Auth::user();	
		if($user->admin){
			$sites = Site::orderBy('id', 'desc')->where("app_name","WordPress")->paginate(50);
		}else{
			$sites = $user->my_sites()->where("app_name","WordPress")->paginate(10);
		}
		
		$success = Input::get('success');
		$site_id = Input::get('site_id');
		$tab_index = "index";
		$current_user = Auth::user(); 
		return view('sites.index', compact('sites','success','site_id','tab_index','current_user'));
	}
	
	public function search()
	{
		$viewsw = "sites";
	    $sites = Site::orderBy('id', 'desc')->where('url', 'like', '%' . Input::get('data') . '%')->paginate(50);
		$data = Input::get('data');
		return view('sites.index', compact('sites','current_user','first_time','data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{   
		$current_user = Auth::user(); 
		return view('sites.create',compact('current_user'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		
		$pete_options = new PeteOption();
		$user = Auth::user();
		$fields_to_validator = $request->all();
		
		$site = new Site();
		$site->output = "";
		$site->user_id = $user->id;
		
		$site->action_name = "New";
		$site->to_clone_project_id = $request->input("to_clone_project_id");
		$site->name = $request->input("name");
		$site->to_import_project = $request->input("to_import_project");
		$site->user_id = $user->id;
		$site->url = $request->input("url");
		
		$site->url = preg_replace("/\s+/", "", $site->url);
		$site->name = preg_replace("/\s+/", "", $site->name);
		
		if($pete_options->get_meta_value('domain_template')){
	
			$site->url = $site->url . "." . $pete_options->get_meta_value('domain_template');
		}
	
		if($site->name){
			
			$forbidden_names = array("filemanager", "ssl", "localhost", "pete", "pete2","html", "Pete", "Pete2");
		
			if (in_array($site->name, $forbidden_names)) {
			    return redirect('sites/create')->withErrors("Forbidden project name");
			}
		}
		
    	$validator = Validator::make($fields_to_validator, [
	   	 'name' =>  array('required', 'regex:/^[a-zA-Z0-9-_]+$/','unique:sites'),
       	 'url' => 'required|unique:sites',
    	 ]);
		 
      	if ($validator->fails()) {
			
 	    	return redirect('sites/create')
 	    		->withErrors($validator)
 	    			->withInput();
 			
      	 }
		
		$site->new_wordpress();
		$site->save();
			
		return Redirect::to('/sites/'.$site->id .'/edit' .'?success=' . 'true');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$site = Site::findOrFail($id);
		$adomains = Adomain::orderBy('id', 'desc')->where('site_id', $site->id)->get();	
		$success = Input::get('success');
		return view('sites.edit', compact('site','adomains','success'));
	}
	
	
	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$user = Auth::user();
		$site = Site::findOrFail($id);
		
		if(($user->id == $site->user_id) || ($user->admin == true)){
			$site->delete_wordpress();
			$site->delete();
			$debug = env('DEBUG');
			if($debug == "active"){
				Log::info('Ouput deleteDebug' . $site->output);
			}
			
		}
		
		return Redirect::to('/?success=true');
	}
	
    public function force_delete(){
	   
	    $user = Auth::user();
 		$site = Site::onlyTrashed()->findOrFail(Input::get('site_id'));	
 		$site->force_delete_wordpress();
 		
		if($user->admin){
			$site->forceDelete();
		}else if($user->id == $site->user_id){
			$site->forceDelete();
		}
		
 		return Redirect::to('sites/trash');
	
    }
	
}

resources/views/sites/_sites_header.blade.php
	
	<div class="row">
            
        <div class="col-md-6">

    			<div class="pete_container">
        			<img alt="w00t!" src="/pete.png" style="height: 204px">
					<p style="font-size: 13px; ">WordPress efficiency starts here.</p>
				</div>
	
		</div>
	
	 <div class="col-md-6">
		 <br /><br />
			 <a style="margin-top: 120px; width: 100%" class="btnpete" href="/sites/create"><i class="glyphicon glyphicon-plus"></i> Create WordPress Instance</a>
		<br />
		<br />
		
		@if($pete_options->get_meta_value('oads') == "active")
		
		<div id="siteWpr">
			<div class="simpleBanner">
				<div class="bannerListWpr">
					
				</div>
				
			</div>
		</div>
		
		@endif
		 
	</div>
	
	</div>

	<div class="row">
				
					<div class="col-md-12">
						
						<a class="table_tab <?php if($tab_index == "index") echo 'index_selected'; ?>" href="/sites">Sites</a>
						
	                    <a class="table_tab <?php if($tab_index == "trash") echo 'index_selected'; ?>" href="/sites/trash">Trash</a>
						
						
					
					</div>
				
	</div>

resources/views/sites/_sites_js.blade.php
<script type="text/javascript">
	
	$(".btnpete").click(function() {
  	  	 activate_loader();
	});
	
		function load_banner(){
	     $.ajax({
	           url: "/get_ads",
	           type: "GET",
	           datatype: 'json',
	           success: function(data){
	            
				html = '<ul class="bannerList">';
			 	for (var item in data) {
					html += '<li><a href="'+data[item].url+'"><img src="{{$dashboard_url}}/ads_images/'+data[item].image+'" /></a></li>';
				}
				html += '</ul>';
				$(".bannerListWpr").html(html);
				$('.simpleBanner').simplebanner({autoRotate: true, rotateTimeout: 3000});
	           }
	
	     });
		}
		
		function check_pete_version(){
			var pete_version = {{$pete_options->get_meta_value('version')}};
			pete_version = parseFloat(pete_version);
			console.log(pete_version);
			
		 	$.ajax({
		 		url: "{{$dashboard_url}}/update_button_json",
		 		dataType: 'JSONP',
		 		type: 'GET',
				data: {parent_version : "{{$pete_options->get_meta_value('parent_version')}}"},
		 		success : function(result) {
					
					last_version = parseFloat(result.version)
					console.log("last_version");
					console.log(last_version);
					
					html="";
					
					if(pete_version < last_version){
					
					<?php if($os_distribution == "darwin"){ ?>
					
					html+='<form class="form-inline" action="/pete_update" method="POST">';
       			 	html+='<input type="hidden" name="script" value="'+result.mac_script+'">';
					html+='<button class="update_pete_button" type="submit">Update</button>';
					html+='</form>';
					
					
					<?php }else if($os_distribution == "ubuntu"){ ?>
					
					html+='<form class="form-inline" action="/pete_update" method="POST">';
       			 	html+='<input type="hidden" name="script" value="'+result.olinux_script+'">';
					html+='<button class="update_pete_button" type="submit">Update</button>';
					html+='</form>';
					
					<?php }else if($os_distribution == "win"){ ?>
					
					html+='<form class="form-inline" action="/pete_update" method="POST">';
       			 	html+='<input type="hidden" name="script" value="'+result.win_script+'">';
					html+='<button class="update_pete_button" type="submit">Update</button>';
					html+='</form>';
					
					<?php } ?>						
					
					}
					
					//$("#update_pete").html('<a class="btnpeteupdate" href="/auth/logout">Update</a>');
					$("#update_pete").html(html);
	           }
	
	     	});
		}
		
		
		$(".clone_action").click(function() {
			site_id = $(this).attr("site_id");
			
		    BootstrapDialog.show({
		          title: 'Clone Site',
		          message: '<label>Domain</label><br /><input class="form-control" id="clone_domain" name="clone_domain" value="">',
		          buttons: [{
		               label: '<a class="form-control">Clone Site</a>',
		              action: function(dialog) {
		                  // submit the form
						  clone_domain = $("#clone_domain").val();
						  site_to_clone_id = site_id;
						 
						  //activate_general_loader();
						  dialog.close();
						  activate_loader();
						  
						$.ajax({
							url: "/clone_site",
							dataType: 'JSON',
							type: 'POST',
							data: {clone_domain : clone_domain, site_to_clone_id: site_to_clone_id},
							success : function(result) {
								
								if(result["message"]){
	
									$.notify({
										icon: "",
										message: result["message"]

									},{
										type: 'info',
										timer: 4000
									});
									$("#loadMe").modal("hide");
									dialog.close();
								    return false;	
									
							  	}else{
									deactivate_loader();
									window.location.href = "/sites?success=true";
							  	}
								
							}		
						});		
						  
		              }
		          }]
		      });
			
		});
	   
	   
		$(".backup_action").click(function() {
			site_id = $(this).attr("site_id");
			
		    BootstrapDialog.show({
		          title: 'Backup Site',
		          message: '<label>Label</label><br /><input class="form-control" id="backup_label" name="backup_label" value="">',
		          buttons: [{
		               label: '<a class="form-control">Backup Site</a>',
		              action: function(dialog) {
		                  // submit the form
						  backup_label = $("#backup_label").val();
						 
						  //activate_general_loader();
						  dialog.close();
						  activate_loader();
						  
						$.ajax({
							url: "/wordpress_backups/create",
							dataType: 'JSON',
							type: 'POST',
							data: {backup_label : backup_label, site_id: site_id},
							success : function(result) {
								
								if(result["message"]){
	
									$.notify({
										icon: "",
										message: result["message"]

									},{
										type: 'info',
										timer: 4000
									});
									$("#loadMe").modal("hide");
									dialog.close();
								    return false;	
									
							  	}else{
									deactivate_loader();
									window.location.href = "/wordpress_backups";
							  	}
								
							}		
						});		
						  
		              }
		          }]
		      });
			
		});
		
		
		
	
    	$(document).ready(function(){
			
			load_banner();
			check_pete_version();
			
  			@if(isset($exporturl))
				console.log("download url: {{$exporturl}}");
  		  		window.location.assign("/{{$exporturl}}");
  		
  		  	@endif
				
			   @if(isset($success))
	
				@if($success == "true")
	
			    var delayInMilliseconds = 3000; //1 second

			    setTimeout(function() {
			      //your code to be executed after 1 second
			   	 $("#loadMe").modal("hide");
			    }, delayInMilliseconds);
	
			     $.ajax({
			           url: "/reload_server",
			           type: "get",
			           datatype: 'json',
			           success: function(data){
           
					       console.log("Reload server success!");

			           }

			     });

			    @endif
	 
			  @endif	
		  

    	});
				
</script>

resources/views/sites/create.blade.php
@extends('layout')

@section('header')

	
@endsection

@section('content')
@include('error')

   
			
<form action="{{ route('sites.store') }}" id ="SiteForm" method="POST" enctype="multipart/form-data">

	<input type="hidden" name="_token" value="{{ csrf_token() }}">          
	<div class="row">
		<div class="col-md-12">
			
			<div class="page-header">
				<h3> Create New WordPress Instance</h3>
				
				
			
			</div>
			
			
	<p>Project name</p>
	<input type="text" id="name-field" name="name" class="form-control" value="" required="" aria-required="true"> <br />
                   								
									
			@if(isset($error))
			
			<div class="alert alert-danger">
				<p>There were some problems with your input.</p>
				<ul>
					@if($site->error_message1)
					<li><i class="glyphicon glyphicon-remove"></i>{{$site->error_message1}}</li>
					@endif
							
					@if($site->error_message2)
					<li><i class="glyphicon glyphicon-remove"></i>{{$site->error_message2}}</li>
					@endif
							
				</ul>
			</div>
			
			@endif
				
			
				 
		</div>
	</div>
							 
			
	@if($pete_options->get_meta_value('domain_template'))
							
						    
	<div class="row">
		<div class="col-md-12">
						
			
				<p>URL</p>
				<input type="text" id="url-field" name="url" class="inline_class url_wordpress_laravel" required/>
				<div id="url_wordpress_helper" class="inline_class">.{{$pete_options->get_meta_value('domain_template')}}</div>
				 <br /><br /><br />
			
		</div>
				
	</div>
							
	@else
						  
	<div class="row">
		<div class="col-md-12">
									
			<div class="form-group" id="url_div">
				<p>URL</p>
				<input type="text" id="url-field" name="url" class="form-control " value="{{ old("url") }}" required/>
				<br /><br /><br />
					   
			</div>
		</div>
	</div>
						  
	@endif
							
                    
               
	<button type="submit" id="create_button" class="btnpete">Create</button>
	<br /><br />
</form>
			
			
			

  
@endsection

resources/views/sites/index.blade.php
@extends('layout')

@section('header')

@endsection

@section('content')

	@include('sites/_sites_header')
	
    <div class="row">
        <div class="col-md-12">
			
			
			<div class="content table-responsive">
            @if($sites->count())
                <table style="padding-left: 10px; padding-right: 10px;" class="table table-hover table-striped">
                    <thead>
                        <tr>
                         <th>Id</th>
                        <th>Project Name</th>
                        <th>Url</th>
                        <th>Action</th>
						<th>App</th>
                         <th class="text-right">Options</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($sites as $site)
                            <tr>
                                <td>{{$site->id}}</td>
                     <td>{{$site->name}}</td>           
                    <td>
					<a href="http://{{$site->url}}" target ='_blank'>{{$site->url}}</a>
					</td>
                   
                    <td>{{$site->action_name}}</td>
					<td>{{$site->app_name}}
					
						@if($site->app_name == "WordPress+Laravel")
							@if($site->action_name == "New")
							<br />
							Laravel version: {{$site->laravel_version}}
							@endif
						@endif
					
					</td>
					
                                <td class="text-right">
                                   
								    <a class="option_button" role="group" href="{{ route('sites.edit', $site->id) }}"> Options</a>
                                  
								   @if($site->app_name != "WordPress+Laravel")
								   <a class="option_button clone_action" id="clone_{{$site->name}}" site_id="{{$site->id}}" href="#"> Clone</a>
								   
								   <a class="option_button" href="/sites/export?id={{$site->id}}">Export</a>
								   
								   @if($pete_options->get_meta_value('obackups') == "active")
								   
								   <a class="option_button backup_action" id="create_backup_{{$site->name}}" site_id="{{$site->id}}" href="#">Create Backup</a>
								   
								   @endif
									 
									@if(!$site->suspend)
									<a class="option_button" id="suspend_{{$site->name}}" href="/sites/suspend?id={{$site->id}}">Suspend</a>
									@else
									<a class="option_button" id="continue_{{$site->name}}" href="/sites/site_continue?id={{$site->id}}">Continue</a>
									@endif
									
									@endif
									
                                    <form action="{{ route('sites.destroy', $site->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" id="delete_{{$site->name}}" class="option_button" style="background-color: #f1592a; width: 100%">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $sites->render() !!}
            @else
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                           	<th>Project Name</th>
                        	<th>Url</th>
                        	<th>Action</th>
							<th>App</th>
                         	<th class="text-right">Options</th>
                        </tr>
                    </thead>

                    <tbody>
					</tbody>
					
				</table>
            @endif
			</div>
        </div>
    </div>
	
	
	
	<div class="modal fade">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	        <h4 class="modal-title">Modal title</h4>
	      </div>
	      <div class="modal-body">
			<form id="site_form" action="/snapshot_creation" style="display:none" method="POST">
				<input type="hidden" name="_method" value="POST">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">         
			    <input type="hidden" id="snapshot_label_form" name="snapshot_label_form" value="">
				<input type="hidden" id="site_id_form" name="site_id_form" value="">
			    <input type="submit" />
			</form>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <button type="button" class="btn btn-primary">Save changes</button>
	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	@include('sites/_sites_js')

@endsection

resources/views/sites/trash.blade.php
@extends('layout')

@section('header')
   
@endsection

@section('content')

	@include('sites/_sites_header')
	
    <div class="row">
		
        <div class="col-md-12">
			
			<div class="content table-responsive">
				
            @if($sites->count())
                <table style="padding-left: 10px; padding-right: 10px;" class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                           <th>Name</th>
                        <th>Url</th>
                        
                        <th>Action</th>
						<th>App</th>

                         <th class="text-right">Options</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($sites as $site)
                            <tr>
                                <td>{{$site->id}}</td>
                     <td>{{$site->name}}</td>           
                    <td>
					<a href="http://{{$site->url}}" target ='_blank'>{{$site->url}}</a>
					</td>
                    
                    <td>{{$site->action_name}}</td>
					<td>{{$site->app_name}}</td>
					
                                <td class="text-right">

								    <a class="option_button" href="/sites/restore?id={{$site->id}}"></i>Restore</a>

									@if($current_user->admin)
									
                                    <form action="/force_delete" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="site_id" value="{{$site->id}}">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="option_button" style="background-color: #f1592a; width: 100%">Force delete</button>
                                    </form>
									
									
									 @endif
									
                                   
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $sites->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif
			</div>
        </div>
    </div>
	
	@include('sites/_sites_js')

@endsection